project:
  type: website
  output-dir: docs

website:
  title: "Christoph Scheuch"
  site-url: https://christophscheuch.github.io/
  description: "Christoph Scheuch"
  favicon: favicon.ico
  open-graph: true
  page-navigation: true
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    section-divs: true
    number-sections: false
    embed-resources: false
    anchor-sections: true
    smooth-scroll: true
    include-in-header: header.html

